# Site settings
title: "liminal notes | jonathan simmons"
description: "The official portfolio and blog of Jonathan Simmons. Features academic and public writing on secularism, culture, and communication."
url: "https://www.liminalnotes.ca"
baseurl: ""
repository: "jssimmon/liminal-notes"

# Theme settings
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark"

# Author settings
author:
  name: "Jonathan Simmons"
  bio: "Research and writing on sociology, secularism, and culture."

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false # <-- Hides author profile from blog posts by default
      show_date: true      # <-- This will display the date on your blog posts
      read_time: true
      comments: # true
      share: true
      related: true

# Scripts applied to the footer
footer_scripts:
  - /assets/css/custom.scss